name: CI workflow

on: 
  push:
    branches:
      - main
  pull_request:
    branches : ["main"]
    
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps: 
      - name: checkout
        uses: "actions/checkout@v3"

      - name: Install dependencies
        run: | 
          python3 -m pip install --upgrade pip
          pip3 freeze > requirement.txt
          pip install -r requirement.txt
    
      - name: Lint with flake8
        run: |
          pip3 install flake8
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
      - name: Run unit test with coverage
        run: 
          python -m unittest discover
